#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the 10 first terms will be:
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def fibonacci(n):
    a, b = 1,2

    Nums=[]
    if n<11:
        for _ in range(n):
            Nums.append(a)
            a, b = b, a + b
    return Nums
def fibsum(limit):
    Sum=0
    a, b = 1,2
    while a < limit:

        if a%2==0:
            Sum+=a
            
        a, b = b, a + b
    
    return Sum

print(fibonacci(10))
print(fibsum(4000000))
